// tocoちゃんバス 時刻表データ (2025年版)
// PDF (66996.pdf) より更新

const CIRCUITS = [
  {
    id: 1,
    name: '南西',
    color: '#16a34a',
    bg: '#dcfce7',
    // 下笹目 発 を基準とした出発時刻
    departures: [
      '8:00','9:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:10','18:10'
    ],
    note: '17時台・最終(18時台)は10分繰り下げ運行',
    stations: [
      { id:0,  name:'下笹目',              offset:0  },
      { id:1,  name:'下町橋',              offset:1  },
      { id:2,  name:'笹目公園',            offset:2  },
      { id:3,  name:'笹目七丁目',          offset:3  },
      { id:4,  name:'早瀬公園',            offset:4  },
      { id:5,  name:'早瀬二丁目',          offset:5  },
      { id:6,  name:'早瀬会館',            offset:7  },
      { id:7,  name:'戸田公園大橋',        offset:11 },
      { id:8,  name:'下町さくら西ひろば',  offset:12 },
      { id:9,  name:'金森橋',              offset:13 },
      { id:10, name:'新曽南三丁目',        offset:14 },
      { id:11, name:'南町',                offset:15 },
      { id:12, name:'大前橋',              offset:16 },
      { id:13, name:'戸田公園駅西口',      offset:25 }, // 着18・10分停車・発25
      { id:14, name:'本町五丁目',          offset:27 },
      { id:15, name:'ボートコース入口',    offset:28 },
      { id:16, name:'県営戸田公園',        offset:32 },
      { id:17, name:'旭が丘',              offset:33 },
      { id:18, name:'ボートコース入口②',  offset:34 },
      { id:19, name:'戸田公園駅南',        offset:36 },
      { id:20, name:'上戸田南保育園',      offset:37 },
      { id:21, name:'南町②',              offset:38 },
      { id:22, name:'新曽南三丁目②',      offset:39 },
      { id:23, name:'給食センター入口',    offset:40 },
      { id:24, name:'戸田公園大橋②',      offset:41 },
      { id:25, name:'笹目川排水機場',      offset:44 },
      { id:26, name:'早瀬二丁目②',        offset:46 },
      { id:27, name:'聖橋',                offset:48 },
      { id:28, name:'笹目六丁目',          offset:49 },
    ]
  },
  {
    id: 2,
    name: '喜沢',
    color: '#d97706',
    bg: '#fef3c7',
    // 戸田公園駅西口 発 を基準とした出発時刻
    departures: [
      '7:40','8:10','8:40','9:10','9:40','10:10','10:40','11:10','11:40',
      '12:10','12:40','13:10','13:40','14:10','14:40','15:10','15:40',
      '16:10','16:40','17:10','17:40','18:10'
    ],
    note: '30分間隔運行',
    stations: [
      { id:0,  name:'戸田公園駅西口',      offset:0  },
      { id:1,  name:'戸田公園北',          offset:0  },
      { id:2,  name:'こどもの国',          offset:1  },
      { id:3,  name:'戸田中央総合病院',    offset:2  },
      { id:4,  name:'上戸田二丁目',        offset:3  },
      { id:5,  name:'戸田市役所南',        offset:5  },
      { id:6,  name:'上戸田稲荷',          offset:7  },
      { id:7,  name:'中島病院',            offset:9  },
      { id:8,  name:'戸田東中学校北',      offset:10 },
      { id:9,  name:'中町一丁目北',        offset:11 },
      { id:10, name:'中町公園',            offset:12 },
      { id:11, name:'カリン通り',          offset:14 },
      { id:12, name:'とだ小林医院',        offset:15 },
      { id:13, name:'喜沢一丁目',          offset:15 },
      { id:14, name:'喜沢記念会館',        offset:16 },
      { id:15, name:'喜沢小学校南',        offset:17 },
      { id:16, name:'アリスの広場東',      offset:18 },
      { id:17, name:'喜沢橋',              offset:19 },
      { id:18, name:'喜沢南一丁目',        offset:21 },
      { id:19, name:'喜沢中学校',          offset:22 },
      { id:20, name:'喜沢南二丁目',        offset:23 },
      { id:21, name:'中町多目的広場',      offset:23 },
      { id:22, name:'こぶし公園前',        offset:24 },
      { id:23, name:'障害者福祉会館北',    offset:27 },
      { id:24, name:'戸田南小学校南',      offset:27 },
    ]
  },
  {
    id: 3,
    name: '川岸',
    color: '#dc2626',
    bg: '#fee2e2',
    // 戸田公園駅西口 発 を基準とした出発時刻
    departures: [
      '7:25','7:55','8:25','8:55','9:25','9:55','10:25','10:55','11:25','11:55',
      '12:25','12:55','13:25','13:55','14:25','14:55','15:25','15:55',
      '16:25','16:55','17:25','17:55','18:25'
    ],
    note: '30分間隔運行',
    stations: [
      { id:0,  name:'戸田公園駅西口',          offset:0  },
      { id:1,  name:'戸田公園北',              offset:1  },
      { id:2,  name:'こどもの国',              offset:1  },
      { id:3,  name:'戸田中央総合病院',        offset:2  },
      { id:4,  name:'戸田第一小学校',          offset:4  },
      { id:5,  name:'後谷会館',                offset:5  },
      { id:6,  name:'戸田市役所',              offset:7  },
      { id:7,  name:'蕨警察署南',              offset:8  },
      { id:8,  name:'市民活動支援センター入口', offset:10 },
      { id:9,  name:'上戸田稲荷',              offset:12 },
      { id:10, name:'中島病院',                offset:14 },
      { id:11, name:'戸田東中学校北',          offset:15 },
      { id:12, name:'公団前',                  offset:16 },
      { id:13, name:'中町二丁目',              offset:17 },
      { id:14, name:'正覚院前',                offset:18 },
      { id:15, name:'中町多目的広場北',        offset:18 },
      { id:16, name:'こぶし公園前',            offset:20 },
      { id:17, name:'川岸二丁目',              offset:21 },
      { id:18, name:'障害者福祉会館前',        offset:22 },
      { id:19, name:'川岸会館前',              offset:22 },
      { id:20, name:'川岸南',                  offset:25 },
      { id:21, name:'川岸一丁目',              offset:27 },
      { id:22, name:'ボートコース入口',        offset:28 },
    ]
  },
  {
    id: 4,
    name: '西',
    color: '#2563eb',
    bg: '#dbeafe',
    // 下笹目 発 を基準とした出発時刻
    departures: [
      '7:30','8:30','9:30','10:30','11:30','12:30','13:30','14:30','15:30','16:30','17:30','18:30'
    ],
    note: '1時間間隔運行',
    stations: [
      { id:0,  name:'下笹目',              offset:0  },
      { id:1,  name:'笹目',                offset:1  },
      { id:2,  name:'笹目東小学校入口',    offset:2  },
      { id:3,  name:'公平病院',            offset:3  },
      { id:4,  name:'笹目南町',            offset:4  },
      { id:5,  name:'新曽氷川神社',        offset:5  },
      { id:6,  name:'新曽口',              offset:7  },
      { id:7,  name:'新曽小学校入口',      offset:8  },
      { id:8,  name:'馬場',                offset:10 },
      { id:9,  name:'浅間橋',              offset:11 },
      { id:10, name:'本町三丁目',          offset:12 },
      { id:11, name:'戸田公園駅西口',      offset:20 }, // 着15・10分停車・発20
      { id:12, name:'多磯院',              offset:22 },
      { id:13, name:'五差路',              offset:23 },
      { id:14, name:'二枚橋',              offset:24 },
      { id:15, name:'新曽柳原',            offset:25 },
      { id:16, name:'沖内',                offset:26 },
      { id:17, name:'戸田駅',              offset:31 },
      { id:18, name:'健康福祉の杜',        offset:33 },
      { id:19, name:'戸田翔陽高校',        offset:35 },
      { id:20, name:'スポーツセンター',    offset:37 },
      { id:21, name:'図書館・博物館',      offset:38 },
      { id:22, name:'図書館南',            offset:39 },
      { id:23, name:'新曽芦原',            offset:40 },
      { id:24, name:'境橋',                offset:41 },
      { id:25, name:'笹目一丁目',          offset:42 },
      { id:26, name:'笹目二丁目',          offset:44 },
      { id:27, name:'児童センター',        offset:45 },
      { id:28, name:'笹目コミュニティセンター', offset:47 },
      { id:29, name:'ささめ幼稚園',        offset:49 },
    ]
  },
  {
    id: 5,
    name: '美笹',
    color: '#9333ea',
    bg: '#f3e8ff',
    // 下笹目 発 を基準とした出発時刻
    departures: [
      '7:30','8:30','9:30','10:30','11:30','12:30','13:30','14:30','15:30','16:30','17:30','18:30'
    ],
    note: '1時間間隔運行',
    stations: [
      { id:0,  name:'下笹目',                offset:0  },
      { id:1,  name:'ささめ幼稚園',          offset:1  },
      { id:2,  name:'笹目コミュニティセンター', offset:3 },
      { id:3,  name:'最勝寺',                offset:5  },
      { id:4,  name:'市民医療センター',      offset:6  },
      { id:5,  name:'山宮',                  offset:6  },
      { id:6,  name:'笹目四丁目',            offset:7  },
      { id:7,  name:'惣右衛門公園',          offset:9  },
      { id:8,  name:'谷口',                  offset:10 },
      { id:9,  name:'笹目北町',              offset:10 },
      { id:10, name:'北部公園西',            offset:11 },
      { id:11, name:'北部公園野球場',        offset:12 },
      { id:12, name:'北戸田駅',              offset:20 }, // 着15・10分停車・発20
      { id:13, name:'北部公園野球場②',      offset:22 },
      { id:14, name:'美女木東一丁目',        offset:23 },
      { id:15, name:'南陵高校',              offset:24 },
      { id:16, name:'美女木小学校入口',      offset:26 },
      { id:17, name:'新田公園',              offset:27 },
      { id:18, name:'藪雨',                  offset:28 },
      { id:19, name:'美女木二丁目',          offset:29 },
      { id:20, name:'美女木一丁目',          offset:30 },
      { id:21, name:'美女木一丁目会館',      offset:31 },
      { id:22, name:'美女木一丁目西',        offset:32 },
      { id:23, name:'美女木',                offset:34 },
      { id:24, name:'番匠免',                offset:37 },
      { id:25, name:'道満',                  offset:48 }, // 着38・10分停車・発48
      { id:26, name:'堀之内',                offset:49 },
      { id:27, name:'修行目',                offset:50 },
      { id:28, name:'美笹支所',              offset:51 },
      { id:29, name:'天王',                  offset:51 },
      { id:30, name:'天王公園',              offset:52 },
    ]
  }
];
