name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm install
        working-directory: ./_blog
      - run: npm install -g hexo
        working-directory: ./_blog
      - run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ github.actor }}"
      - run: hexo generate && hexo deploy
        working-directory: ./_blog
