name: deploy
on:
  push:
    branches:
      - release
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm install
        working-directory: ./_blog
      - run: npm install -g hexo
        working-directory: ./_blog
      - run: npm install hexo-deployer-git --save
        working-directory: ./_blog
      - run: npm run build
        working-directory: ./_blog
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: .
