name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: ./_blog
      - run: yarn global hexo
        working-directory: ./_blog
      - run: yarn run build
        working-directory: ./_blog
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: .
